### ISSUE TITLE
Observações longas

### ISSUE THREAD

**Issue by ricsalvares** [mcfox/ruby_danfe#41]
Comecei a utilizar a gem há alguns dias e está tudo indo bem, entretanto quando eu adiciono uma observação (<infCpl>)relativamente grande não é desenhada, além de replicar sempre os mesmos `n`* primeiros caracteres em todas as páginas.
Alguma sugestão de como corrigir esse problema?

* para os testes que fiz, `n` varia de aproximadamente 900 caracteres maiúsculos e aproxiadamente 1500 caracteres minúsculos, sendo que no manual aceita até 5000 caracteres

**Comment by jlneto** [comment]
Isso é uma limitação de espaço, poderiamos diminuir o fonte o tentar aumentar o espaço onde e impressa a observação, mas para isso deveriamos adicionar algumas opções de configuração da gem. Se quiser fazer um PR com isso podemos avaliar. Pelo tempo do chamado vou encerrar, se quiser crie um outro para tratar isso.
