### ISSUE TITLE
Erro ao gerar CTe

### ISSUE THREAD

**Issue by rafarosa92** [mcfox/ruby_danfe#62]
pdf = RubyDanfe.generatePDF(xml_response)

*** Prawn::Errors::EmptyTable Exception: data must be a non-empty, non-nil, two dimensional array of cell-convertible objects

Caso precisem posso enviar o xml para teste

**Comment by gabrielescodino** [comment]
Opa @rafarosa92 
Pode me mandar o xml que você está tentando gerar para eu verificar, por favor?

**Comment by rafarosa92** [comment]
Enviei por email...

**Comment by JoaoPeterli** [comment]
Boa noite amigo estou  tendo o mesmo erro que nosso colega rafarosa92

**Comment by rafarosa92** [comment]
eu acabei pegando um código que tinha em php, coloquei no meu servidor e está rodando, se você quiser usar pode me chamar, te passo a url, basicamente recebo o xml e devolvo o pdf na respota!

**Comment by jlneto** [comment]
Encerrando o chamado por falta de atividade
